name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    # ⚠️ ملاحظة: تأكد من أن هذه الخطوة على نفس مستوى إزاحة "steps" السابقة
    - name: Provide google-services.json
      if: env.GOOGLE_SERVICES_JSON != ''
      run: |
        # المسار الصحيح هنا هو android/app/ إذا كان ملف google-services.json يوجد بداخله
        echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
        # المسار في الأمر ls -l يجب أن يكون متوافقاً مع المسار أعلاه
        ls -l android/app/google-services.json 

    # ⬅️ المسار الصحيح لملف gradlew هو في جذر المستودع
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # استخدام "gradlew" أو "./gradlew"
      
    # ❌ قم بإزالة هذه الخطوة المكررة أو الخاطئة في المسار
    # - name: Make gradlew executable
    #   run: chmod +x app/gradlew 

    # ❌ وقم بإزالة هذه الخطوة أيضاً لأنها أصبحت مكررة للخطوة أعلاه
    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./app/gradlew build
