name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    # ⚠️ ملاحظة: تأكد من أن هذه الخطوة على نفس مستوى إزاحة "steps" السابقة
    - name: Provide google-services.json
      if: env.GOOGLE_SERVICES_JSON != ''
      run: |
        # المسار الصحيح هنا هو android/app/ إذا كان ملف google-services.json يوجد بداخله
        echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
        # المسار في الأمر ls -l يجب أن يكون متوافقاً مع المسار أعلاه
        ls -l android/app/google-services.json 

- uses: actions/checkout@v4
# ... خطوات setup-java ...

# منح الإذن داخل المجلد
- name: Grant execute permission for gradlew
  run: chmod +x gradlew
  working-directory: app # ⬅️ سيتم تنفيذ الأمر داخل مجلد "android/"

# البناء باستخدام المسار داخل المجلد
- name: Build with Gradle
  run: ./gradlew build
  working-directory: app # ⬅️ سيتم تنفيذ الأمر داخل مجلد "android/"
